            - name: Upload GitHub Pages artifact
  uses: actions/upload-pages-artifact@v2.0.0
  with:
    # Artifact name
    name: # optional, default is github-pages
    # Path of the directory containing the static assets.
    path: # default is _site/
    # Duration after which artifact will expire in days.
    retention-days: # optional, default is 1
